---
title: "Self & Peer Evaluations"
subtitle: "Stat 184 Final Project"
author: William Bressner
date: now
format: pdf
---
<!--Directions
Use this RMD template to complete peer and self evaluations for your final project. Be sure to answer all prompts for each team member and yourself. You'll upload the knitted PDF (not the RMD) to the appropriate Canvas Portal.
--->


# Team Member 1

## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*
Donovan Carmichael


## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): _10__

Justification/Examples: Donovan was very organized and did a great job.




#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): _10__

Justification/Examples: We worked well together.




#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples: He contributed and communicated well within the group.




#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): _10__

Justification/Examples: He was good with his time management and keeping track of time.





#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): _10__

Justification/Examples: It was a pleasure doing this project with him. 





### Total Score (out of 50): 50


# Team Member 2

## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*
Jake Sturges

## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): _10__

Justification/Examples: Jake had a great understanding of the project and interpreting data.




#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): _10__

Justification/Examples: He was committed to the project and easy to work with.




#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples: He effectively contributed and communicated with the team.




#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): _10__

Justification/Examples: He followed through with plans and we worked well together.





#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): _10__

Justification/Examples: I really enjoyed working on this project with Jake.





### Total Score (out of 50): 50


# Team Member 3

## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*
Self-Evaluation

## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): _10__

Justification/Examples: I completed my part of the project and worked well with my group members.




#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): _10__

Justification/Examples: I listed to my teammate's ideas and respected their ideas. I was flexible and cooperated well with my group members.




#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples: I effectively communicated with my team and had a good contribution towards the project.




#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): _10__

Justification/Examples: I met up with my team members and we did things on time.





#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): __10_

Justification/Examples: I had a great experience working with my team on this final project.





### Total Score (out of 50): 50

